site_name: Portal Técnico e-saúdeSP
site_description: Documentação técnica para implementação e homologação (CDEM-RAC e RISAH).

theme:
  name: material
  language: pt-BR
  logo: logo.png      
  favicon: logo.png   
  palette:
    # ALTERE AS DUAS LINHAS ABAIXO 👇
    primary: teal
    accent: teal
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Guia de Introdução:
      - Comece por aqui: comece-por-aqui.md
      - Base Normativa: base-normativa.md
  - Modelos de Informação:
      - Modelo de Informação Vigente:
          - CMD (Atendimento): cmd.md
      - Modelo de Informação em Implementação:
          - CDEM-RAC (Ambulatorial): cdem-rac.md
          - RISAH (Hospitalar): risah.md
  - Desenvolvimento Técnico:
      - Especificação FHIR: especificacao.md
      - Guia de Integração: integracao.md
      - Sandbox: sandbox.md
  - Governança e Apoio:
      - Homologação: homologacao.md
      - Downloads: downloads.md
      - Suporte: suporte.md
      - Histórico de Versões: changelog.md
